.\" This is a manual page for the X11 game "3D Pong".  It was written
.\" by mace <mace@pcuf.fi>, independently of the software development
.\" itself.
.\"
.\" This manual page is protected by the GNU General Public License.
.\"
.\" $Id$
.TH 3dpong 6 "28/04/2004" "" "Games"
.SH NAME
3dpong \- three dimensional Pong clone
.SH SYNOPSIS
.B 3dpong
.I display1
.RB [\| display2 | \-\-computer \|]
.RB [\| \-\-gravity
.IR g \|]
.RB [\| \-\-net
.IR n \|]
.RB [\| \-\-sound \|]
.RB [\| \-\-noclick1 \|]
.RB [\| \-\-noclick2 \|]
.SH DESCRIPTION
.B 3D Pong
is a three-dimensional clone of the ancient computer game Pong for the
X11 window system.
.P
There are three modes of play
.TP
one player
One player mode agains the computer
.TP
two players
Two human players, each with their own view at the game
.TP
handball
One human player against gravity.  This is like throwing a ball at a wall
.P
The player(s) is presented a three dimensional view at the arena.
There is a white divider in the middle, or possibly the net.  The
player one's paddle is a red square, the player two has a blue paddle.
The current score is displayed in the upper left corner.  The ball is
a green diamond, and dark green markers follow the ball on the walls
to display it's position in relation to them.
.P
The player(s) controls a paddle at one end of the arena with mouse
movement.  To serve, the player presses the mouse button three.  The
key
.B c
toggles whether the player needs to keep the mouse button one pressed
while dragging the mouse.  See also the
.BI \-\-noclick n
switches below.
.P
Six views exist, switched amongst with the key
.B v
.TP
normal
1st person perspective from behind the paddle
.TP
bleacher
Side view, with the paddle on the left
.TP
above
From above, paddle on the top
.TP
freeview
Any angle the user selects, by pressing mouse button two and
dragging the mouse
.TP
follow the ball
The view follows the ball
.TP
follow the paddle
The view follows the paddle
.P
Key
.B 3
toggles red/blue mode to be used with appropriate 3D glasses, with red
for the left eye.
.P
The game quits if the
.B q
key is pressed.
.P
The game goes on until quitted.  In the one or two player games the
ball gets faster and faster until someone scores.  Players score by
getting the ball behind the opponents paddle.  In the handball mode
the player scores every time the ball bounces off the paddle, and does
not go to the goal.  The high score will kept for the session.
.SH OPTIONS
The switches
.BR display1 \ and \ display2
specify the X11 displays for the game.  The first is mandatory, and
.SB ``$DISPLAY''
is often a good value for it.  The special value
.B ``computer''
means that only one human player is to play, the other will be a
computer player.  If only one display is specified, then a handball
game is started.
.P
Attention to the order of the options must be payed.
.TP
.BI \-\-gravity \ g
The gravity to use.  In one and two player games, this is toward the
floor, and in the handball it is toward the paddle.  Minimum gravity for
handball game is 0.1, and negative values are not allowed, unlike in the
other two modes.  A synonym for the switch is
.BI \-g \ g
.TP
.BI \-\-net \ n
To use a net in the one or two player modes, use this switch.  The value of
.I n
must be 0>\fIn\fR>0.75.  The net will be in the middle, between the
two players and when the ball hits it, it will bounce back at full
force.  The maximum height, 0.75, is two thirds of the height of the
game arena.  A synonym for this switch is
.BI \-n \ n
The net option must not appear before the gravity option.
.TP
.B \-\-sound
To use sound in the game, use this switch or it's synonym
.BR \-s .
This must appear after the optional net switch.
.P
The switches
.BR \-\-noclick1 \ and \-\-noclick2
mean that the specified player need not to keep the mouse button 1
pressed down.  Such options must appear last on the command line.  The
key
.B c
can also be used to toggle this while the game is running.
.SH NOTES
This manual page documents the
.B 3D Pong
version 0.5, and is based on the \fCREADME.txt\fR file in the distribution.
.SH AUTHOR
The game is written by Bill Kendrick
\fC<bill@newbreedsoftware.com>\fR, and this manual page was written
independetly of the actual software by mace \fC<mace@pcuf.fi>\fR.  The
game sounds originally appeared in the game
.BR xboing (6x).
